#!/bin/bash
#SBATCH -J dataqual
#SBATCH --partition=compute
#SBATCH --nodes=1
#SBATCH --mem=128G
#SBATCH --account=csd403
#SBATCH --no-requeue
#SBATCH -t 24:00:00
#SBATCH --ntasks-per-node=1
#SBATCH --output="/expanse/projects/nemar/openneuro/processed/logs/process_all/dataqual.%j.out"
#SBATCH -e /expanse/projects/nemar/openneuro/processed/logs/process_all/dataqual.%j.err
cd /home/dtyoung/NEMAR-pipeline/sbatch
module load matlab/2022b
matlab -nodisplay -r "process_all_dataqual();"
